<?php
/**
 * Created by PhpStorm.
 * Author: 火柴<290559038@qq.com>
 * Date: 2017/11/14
 * Time: 21:10
 */

namespace sale\models;


use common\models\Company;
use yii\base\Model;

class CompanyForm extends Model
{
    public $company_name;
    public $industry_id;
    public $province_id;
    public $city_id;
    public $scale;
    public $mobile;
    public $website;
    public $instroduce;
    public $remarks;

    public function rules()
    {
        return [
            ['co', 'trim'],
            ['username', 'required'],
            ['username', 'unique', 'targetClass' => '\common\models\Admin', 'message' => '此{attribute}已经被注册'],
            ['username', 'string', 'min' => 2, 'max' => 255],

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'targetClass' => '\common\models\Admin', 'message' => '此{attribute}已经被注册'],

            ['password', 'required'],
            ['password', 'string', 'min' => 6],
        ];
    }



    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}